### PR TITLE
Responsive

### PR DESCRIPTION
**Pull request by jcromerohdz**

### CODE REVIEW

**Comment by whiz25** [comment]
# Good job guys :thumbsup:
@lhscar56 , @jcromerohdz 
You have done an awesome job given that it is your first PR.
However, we need to fix a few crucial requirements before we can complete this project.
The following are the sections to be fixed.
# General page structure
- [x] search icon should be at the rightmost side of sub-navigation row on ```large screen``` and ```medium screen```
- [x] the TNW logo should disappear on a medium screen

# Specifics
## Latest news section
- [x] add a header with section name
- [x] display three articles per row on ```medium screen```
- [x] images should not overlap with text on ```small screen```
## Latest Funding section
- [x] align three articles per row on ```medium screen```
## Apps, GERA, Tech, etc section
- [x] align two category boxes per row
## Latest deals section
- [x] properly align the section title with the images. It should start where the rows start.
- [x] please align only three images per row on ```medium screen```
- [x] images should not overlap with text on ```small screen```
## Media queries
- [x] small: max-width around 700
- [x] medium: max-width around 1000
- [x] large: min-width over 1000
## Other must-haves
- [x] Update your ```README``` to look more professional. Add details on how to clone the project, the stacks used, contributors, etc.
- [x] Add ```.vscode``` folder to ```git ignore```
- [ ] Delete all comments from your code

Please work on those changes and submit for another review.

**Review by whiz25 — CHANGES_REQUESTED** [review]
Your linting has passed all tests. That's good.
Look at my comments and make those changes and submit another review.

**Review by Ispirett — CHANGES_REQUESTED** [review]
Great Job!! This project and changes folks.

image


**Optional** **Fixes**
You can add some padding to your text here to give it some breathing room.
hello

**Html Errors**
please correct  errors using this [link](https://validator.w3.org/)

submit for re-review when finished.

**Review by Ispirett — APPROVED** [review]
Great job folks, you can now merge this project :+1:  :100:

**Pull request merged**
